version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  api:
    image: spring-boot-rest-postgres
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db