INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME) VALUES (1, 'iPhone');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME) VALUES (2, 'iPhone SE');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME) VALUES (3, 'iPhone 7');
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME) VALUES (4, 'iPhone 8');